// Mocks generated by Mockito 5.4.0 from annotations
// in rg_rek/test/features/events/data/repository/default_event_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:rg_rek/core/network_info/network_info.dart' as _i2;
import 'package:rg_rek/features/events/data/data_sources/remote/remote_event_data_source.dart'
    as _i4;
import 'package:rg_rek/features/events/data/models/event_model.dart' as _i5;
import 'package:rg_rek/features/events/data/models/event_snapshot_model.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i2.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}

/// A class which mocks [EventRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockEventRemoteDataSource extends _i1.Mock
    implements _i4.EventRemoteDataSource {
  MockEventRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i5.EventModel>> getEventsByCategory(int? categoryId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEventsByCategory,
          [categoryId],
        ),
        returnValue: _i3.Future<List<_i5.EventModel>>.value(<_i5.EventModel>[]),
      ) as _i3.Future<List<_i5.EventModel>>);
  @override
  _i3.Future<List<_i6.EventSnapshotModel>> getEventSnapshotsByPhrase(
          String? phrase) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEventSnapshotsByPhrase,
          [phrase],
        ),
        returnValue: _i3.Future<List<_i6.EventSnapshotModel>>.value(
            <_i6.EventSnapshotModel>[]),
      ) as _i3.Future<List<_i6.EventSnapshotModel>>);
}
