// Mocks generated by Mockito 5.4.0 from annotations
// in rg_rek/test/features/events/presentation/pages/market/widgets/tab_bar_pages/my_events/widgets/events_by_category_list/bloc/events_by_category_list_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:rg_rek/core/errors/failures.dart' as _i6;
import 'package:rg_rek/features/events/domain/entities/event.dart' as _i7;
import 'package:rg_rek/features/events/domain/repositories/event_repository.dart'
    as _i2;
import 'package:rg_rek/features/events/domain/use_cases/load_events_by_category.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEventRepository_0 extends _i1.SmartFake
    implements _i2.EventRepository {
  _FakeEventRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [LoadEventsByCategory].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoadEventsByCategory extends _i1.Mock
    implements _i4.LoadEventsByCategory {
  MockLoadEventsByCategory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.EventRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeEventRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.EventRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.Event>>> call(
          String? categoryId) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [categoryId],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, List<_i7.Event>>>.value(
            _FakeEither_1<_i6.Failure, List<_i7.Event>>(
          this,
          Invocation.method(
            #call,
            [categoryId],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i7.Event>>>);
}
